# Artifical Neural Network for Housing Rent Dataset 


## Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
tf.__version__

'2.9.2'

## Importing the dataset

In [ ]:
dataset = pd.read_csv("HousingRentDataset.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[1100 2 2 'Kolkata' 'Unfurnished' 'Super Area']
 [800 2 1 'Kolkata' 'Semi-Furnished' 'Super Area']
 [1000 2 1 'Kolkata' 'Semi-Furnished' 'Super Area']
 ...
 [1750 3 3 'Hyderabad' 'Semi-Furnished' 'Carpet Area']
 [1500 3 2 'Hyderabad' 'Semi-Furnished' 'Carpet Area']
 [1000 2 2 'Hyderabad' 'Unfurnished' 'Carpet Area']]


In [ ]:
print(y)

[10000 20000 17000 ... 35000 45000 15000]


## Encoding the dataset

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [3, 4, 5])], remainder='passthrough')
X = transformer.fit_transform(X)

In [ ]:
print(X)

[[0.0 0.0 0.0 ... 1100 2 2]
 [0.0 0.0 0.0 ... 800 2 1]
 [0.0 0.0 0.0 ... 1000 2 1]
 ...
 [0.0 0.0 0.0 ... 1750 3 3]
 [0.0 0.0 0.0 ... 1500 3 2]
 [0.0 0.0 0.0 ... 1000 2 2]]


## Spliting the dataset into train and test set.

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
print(X_train)

[[0.0 0.0 0.0 ... 950 2 2]
 [0.0 0.0 0.0 ... 200 2 2]
 [1.0 0.0 0.0 ... 1200 2 2]
 ...
 [1.0 0.0 0.0 ... 600 1 1]
 [0.0 1.0 0.0 ... 1000 3 2]
 [0.0 0.0 0.0 ... 800 2 2]]


In [ ]:
print(X_test)

[[0.0 0.0 0.0 ... 900 2 2]
 [0.0 0.0 0.0 ... 1092 3 3]
 [0.0 0.0 0.0 ... 628 2 2]
 ...
 [0.0 1.0 0.0 ... 1200 3 3]
 [0.0 0.0 0.0 ... 1600 3 3]
 [0.0 0.0 0.0 ... 650 2 3]]


In [ ]:
print(y_train.shape)

(3559,)


In [ ]:
print(y_test)

[  8000 150000  43000 ...  29000  25000  50000]


## Feature Scaling

In [ ]:
# Reshaping the y data.
y_train = y_train.reshape(len(y_train), 1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [ ]:
print(X_train)

[[-0.47 -0.49 -0.38 ... -0.03 -0.09  0.04]
 [-0.47 -0.49 -0.38 ... -1.21 -0.09  0.04]
 [ 2.11 -0.49 -0.38 ...  0.37 -0.09  0.04]
 ...
 [ 2.11 -0.49 -0.38 ... -0.58 -1.29 -1.09]
 [-0.47  2.05 -0.38 ...  0.05  1.1   0.04]
 [-0.47 -0.49 -0.38 ... -0.26 -0.09  0.04]]


In [ ]:
print(y_train)

[[ 0.24]
 [-0.28]
 [-0.25]
 ...
 [-0.37]
 [-0.21]
 [-0.34]]


# Part-2 Building the ANN

## Initializing the ANN


In [ ]:
ann = tf.keras.models.Sequential()

## Adding the Input and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

## Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

## Adding third hidden layer.

In [ ]:
# ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

## Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

# Part-3 Training the ANN

## Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')

## Training the ANN model on the train dataset

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
112/112 [==============================] - 1s 2ms/step - loss: 1.0620
Epoch 2/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8798
Epoch 3/100
112/112 [==============================] - 0s 2ms/step - loss: 0.7834
Epoch 4/100
112/112 [==============================] - 0s 2ms/step - loss: 0.7277
Epoch 5/100
112/112 [==============================] - 0s 2ms/step - loss: 0.7005
Epoch 6/100
112/112 [==============================] - 0s 2ms/step - loss: 0.6841
Epoch 7/100
112/112 [==============================] - 0s 2ms/step - loss: 0.6730
Epoch 8/100
112/112 [==============================] - 0s 2ms/step - loss: 0.6659
Epoch 9/100
112/112 [==============================] - 0s 2ms/step - loss: 0.6600
Epoch 10/100
112/112 [==============================] - 0s 2ms/step - loss: 0.6565
Epoch 11/100
112/112 [==============================] - 0s 2ms/step - loss: 0.6531
Epoch 12/100
112/112 [==============================] - 0s 2ms/step - loss: 0.6483
Epoch 13/100


## Predicting the result of the test set.


In [ ]:
y_pred = sc_y.inverse_transform(ann.predict(sc_X.transform(X_test)))

38/38 [==============================] - 0s 1ms/step


In [ ]:
np.set_printoptions(precision=2)
np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)

array([[ 10601.78,   8000.  ],
       [109763.05, 150000.  ],
       [ 38811.2 ,  43000.  ],
       ...,
       [ 27659.69,  29000.  ],
       [ 13430.76,  25000.  ],
       [ 53183.67,  50000.  ]])

## Testing the accuracy of the model.

In [ ]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7357315039696767
